Repository defactor-com/documentation, pull requests merged in 2024-08, with the labels that each got.

#123 fix(pools-api-endpoints): fix pools api endpoints documentation
  docs/pools/back-end/api/counterpartyPools/graphql.md
  docs/pools/back-end/api/erc20CollateralToken/graphql.md
  docs/pools/back-end/api/erc20CollateralToken/restful.md
Labels: documentation, enhancement

#130 Update additional-resources.md
  docs/resources/additional-resources.md
Labels: hoji:reviewed

#133 feat: document ipfs endpoints
  docs/pools/back-end/api/ipfs/_category_.json
  docs/pools/back-end/api/ipfs/graphql.md
  docs/pools/back-end/api/ipfs/restful.md
Labels: documentation, hoji:reviewed

#135 docs(engage): udpate contract address for staking contract in staking…
  static/testnet/defactor-engage.json
Labels: hoji:reviewed

#132 Added project onboarding Engage
  docs/engage/how-tos/project-onboarding.md
Labels: hoji:reviewed

#136 docs(engage): update contract address
  static/testnet/defactor-engage.json
Labels: hoji:reviewed
